import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import TodoListPage from './TodoListPage'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next TODO App</title>
        <meta name="description" content="Next TODO app generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TodoListPage />
      </main>
    </div>
  )
}

export default Home
